version: "3.9"

services:
  omnicrossrsm1:
    image: omnicrossrsm
    container_name: omnicrossrsm1
    hostname: omnicrossrsm1
    # volumes:
    #   - ./volumes/volumes/omnicrossrsm1:/data:Z
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
    ports:
      - 8081:8080
    environment: 
      - RUST_BACKTRACE=1
      - PID=1
      - PEERS=2,3
      - PEER_ADDRS=omnicrossrsm2:8080,omnicrossrsm3:8080

  omnicrossrsm2:
    image: omnicrossrsm
    container_name: omnicrossrsm2
    hostname: omnicrossrsm2
    # volumes:
    #   - ./volumes/volumes/omnicrossrsm2:/data:Z
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
    ports:
      - 8082:8080
    environment: 
      - RUST_BACKTRACE=1
      - PID=2
      - PEERS=1,3
      - PEER_ADDRS=omnicrossrsm1:8080,omnicrossrsm3:8080

  omnicrossrsm3:
    image: omnicrossrsm
    container_name: omnicrossrsm3
    hostname: omnicrossrsm3
    # volumes:
    #   - ./volumes/volumes/omnicrossrsm3:/data:Z
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
    ports:
      - 8083:8080
    environment: 
      - RUST_BACKTRACE=1
      - PID=3
      - PEERS=1,2
      - PEER_ADDRS=omnicrossrsm1:8080,omnicrossrsm2:8080
