service: {
  name: omnicross-svc,
}
app: {
  name: omnicross,
}
statefulset: {
  name: omnicross,
  replicas: 4
}


port: {
  container: {
    rsm: {
      name: axum,
      value: 8080,
    },
    app: {
      name: flask,
      value: 5000,
    }
  },
  node: {
    name: external,
    value: 30080,
  }
}

destinations: {
  mapping: {
    1: 2,
    2: 3,
    3: 4,
    4: 1,
  }
}